### ISSUE TITLE
Network error: {"errors":[{"message":"jwt malformed"}]} 

### ISSUE THREAD

**Issue by chrisjaimes** [Camji55/nexus-plugin-jwt-auth#22]
I have the following setup in my app 
```
use(auth({
    appSecret: config.TOKEN_SECRET_KEY,
    protectedPaths
}))
```
However when calling my Query from a front-end app, I get the following error: 

`error Error: Network error: Http failure response for http://localhost:4000/graphql: 500 Internal Server Error`

In the network tab of the browser i see:
`{"errors":[{"message":"jwt malformed"}]}`

Notes: 
- When making the call, I am not passing any Authorization Bearer token (could this be the reason of the error? if so, how can I make calls to some open queries and mutations without the need of having a user authenticated?) 

Thanks!

**Comment by chrisjaimes** [comment]
Not sure what changes I made but I also get `invalid signature` error in the frontend when trying to call the GraphQL nexus endpoint. 
Commenting out this piece
```
use(auth({
    appSecret: config.TOKEN_SECRET_KEY,
    protectedPaths
}))
```
makes both errors go away. Am I missing something?

**Comment by chrisjaimes** [comment]
I downloaded the lib again to my nexus server and requests work fine now from the front-end. Probably it was a bad setting on my side. Somehow it got fixed.

**Comment by Camji55** [comment]
@chrisjaimes That's great to hear! A little busy on my end lately, sorry I wasn't able to help out.
